dubbo:
  application:
    name: common-service
  registry:
    protocol: zookeeper
    address: 192.168.199.129:2181
  protocol:
    port: 28813


spring:
  mail:
    host: smtp.163.com
    username: riyuetian9@163.com
    password: qazqazqaz123
    default-encoding: UTF-8
  rabbitmq:
    host: 192.168.199.129
    port: 5672
    virtual-host: /fang
    username: fang
    password: 123

server:
  port: 8083


mail:
  fromAddr: riyuetian9@163.com
