
dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 192.168.199.129:2181
  protocol:
    port: 28814


spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 999
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.199.129
    port: 6379
    password: 123123
    jedis:
      pool:
        max-active: 66
#        max-wait: