
dubbo:
  application:
    name: register-web
  registry:
    protocol: zookeeper
    address: 192.168.199.129:2181


server:
  port: 9094


spring:
  thymeleaf:
    cache: false

  rabbitmq:
    host: 192.168.199.129
    port: 5672
    virtual-host: /fang
    username: fang
    password: 123

  redis:
    host: 192.168.199.129
    port: 6379
    password: 123123
    jedis:
      pool:
       max-active: 66
