
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.129:3306/miaosha
    username: root
    password: root
  redis:
    host: 192.168.199.129
    password: 123123


mybatis:
  mapper-locations: classpath:/mapper/*.xml
