#\u914D\u7F6E\u6570\u636E\u6E90\u4FE1\u606F
#  useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC\u4E0D\u52A0\u8FD9\u53E5 \u53EF\u80FD\u4F1A\u51FA\u73B0\u65F6\u533A\u5F02\u5E38spring:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 999
    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      filter:
#        config:
#          enabled: true
#      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
#
#public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKyxiY22rhb3iRNDuVYa7jMgvGDgS48snUdwiEypYyaHTVMtu+tkHr2+0Y9AU+fTJFCWmWxTrRS8zatICy5oMYcCAwEAAQ==

#\u53D1\u5E032  \u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u4FE1\u606F   \u8FDC\u7A0B\u768410.38.8.8:2181
dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.199.129:2181
  protocol:
    port: 28810